### ISSUE TITLE
Env Dosyası

### ISSUE THREAD

**Issue by alperenbozkurt** [rerdogantr/jitsiadd#5]
Merhaba, 
Bilmiyorum proje canlıda kullanılıyor mu ama .env dosyasını da pushlamışsınız. Ne olur ne olmaz haber vermek istedim.
İyi Günler.

**Comment by rerdogantr** [comment]
Merhaba, evet sample olarak kullanılabilir. 
Run edilince regenerate oluyor, yine de bazı alanları düzenlemekte fayda var.  Teşekkürler bilgi için.
